services:
  app:
    build: .
    tty: true
    volumes:
      - ./app:/app
    environment:
      - WATCHPACK_POLLING=true
      - NODE_OPTIONS=--openssl-legacy-provider
    ports:
      - "3000:3000"